"""Made changes to the DB

Revision ID: 069981a6b276
Revises: b72c57d2cf05
Create Date: 2025-08-01 20:51:41.905780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '069981a6b276'
down_revision: Union[str, Sequence[str], None] = 'b72c57d2cf05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('transactions', 'created_ar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_ar', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
